/*
 * DBDesigner does not support Constraints.
 * This Script is used to add those constraints separately
 * Version 3.0
 * Added unique constraint to the column code in the table Subject and Program
 * Add unique constraint to USER_ in FORGOTTEN_PASSWORD_KEY
 * add unique constraint to Course for the 3 FK
 * Version 2.0
 ** - Added unique constraint to CONFIRMATION_KEY ,PERIOD, PROGRAM
 ** - Added unique constraint to the tables of Ratings, SUBJECT_RATING,
 **   PROFESSOR_RATING, COURSE_RATING and COMMENT_RATING
 ** - Added uniue constrainto to PROFESSOR in E_MAIL, URL_IMAGE, URL_WEB and (FIRST_NAME, LAST_NAME)
*/

ALTER TABLE USER_ ADD UNIQUE ( USER_NAME );
ALTER TABLE TYPE_FEEDBACK ADD UNIQUE ( NAME );
ALTER TABLE CONFIRMATION_KEY ADD UNIQUE( ID_USER_ );
ALTER TABLE PERIOD_ ADD UNIQUE(YEAR_, SEMESTER);
ALTER TABLE PROGRAM ADD UNIQUE ( NAME );

ALTER TABLE SUBJECT_RATING ADD UNIQUE(ID_USER_, ID_SUBJECT);
ALTER TABLE COURSE_RATING ADD UNIQUE(ID_USER_, ID_COURSE);
ALTER TABLE COMMENT_RATING ADD UNIQUE(ID_USER_, ID_COMMENT_);

ALTER TABLE PROFESSOR ADD UNIQUE ( E_MAIL );
ALTER TABLE PROFESSOR ADD UNIQUE ( URL_IMAGE );
ALTER TABLE PROFESSOR ADD UNIQUE ( URL_WEB );
ALTER TABLE PROFESSOR ADD UNIQUE(FIRST_NAMES, LAST_NAMES);

ALTER TABLE SUBJECT ADD UNIQUE ( CODE );
ALTER TABLE PROGRAM ADD UNIQUE ( CODE );

ALTER TABLE FORGOTTEN_PASSWORD_KEY ADD UNIQUE ( ID_USER_ );

ALTER TABLE COURSE ADD UNIQUE CONSTRAINT (ID_PROFESSOR, ID_SUBJECT, ID_PERIOD);